//go:build !ignore_autogenerated

/*
Copyright (c) 2020 - 2025 SUSE LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleDeployment) DeepCopyInto(out *BundleDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleDeployment.
func (in *BundleDeployment) DeepCopy() *BundleDeployment {
	if in == nil {
		return nil
	}
	out := new(BundleDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BundleDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleDeploymentDisplay) DeepCopyInto(out *BundleDeploymentDisplay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleDeploymentDisplay.
func (in *BundleDeploymentDisplay) DeepCopy() *BundleDeploymentDisplay {
	if in == nil {
		return nil
	}
	out := new(BundleDeploymentDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleDeploymentList) DeepCopyInto(out *BundleDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BundleDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleDeploymentList.
func (in *BundleDeploymentList) DeepCopy() *BundleDeploymentList {
	if in == nil {
		return nil
	}
	out := new(BundleDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BundleDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleDeploymentOptions) DeepCopyInto(out *BundleDeploymentOptions) {
	*out = *in
	in.GitOpsBundleDeploymentOptions.DeepCopyInto(&out.GitOpsBundleDeploymentOptions)
	if in.Helm != nil {
		in, out := &in.Helm, &out.Helm
		*out = new(HelmOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Diff != nil {
		in, out := &in.Diff, &out.Diff
		*out = new(DiffOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.IgnoreOptions != nil {
		in, out := &in.IgnoreOptions, &out.IgnoreOptions
		*out = new(IgnoreOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.CorrectDrift != nil {
		in, out := &in.CorrectDrift, &out.CorrectDrift
		*out = new(CorrectDrift)
		**out = **in
	}
	if in.NamespaceLabels != nil {
		in, out := &in.NamespaceLabels, &out.NamespaceLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NamespaceAnnotations != nil {
		in, out := &in.NamespaceAnnotations, &out.NamespaceAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.DownstreamResources != nil {
		in, out := &in.DownstreamResources, &out.DownstreamResources
		*out = make([]DownstreamResource, len(*in))
		copy(*out, *in)
	}
	if in.Overwrites != nil {
		in, out := &in.Overwrites, &out.Overwrites
		*out = make([]OverwrittenResource, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleDeploymentOptions.
func (in *BundleDeploymentOptions) DeepCopy() *BundleDeploymentOptions {
	if in == nil {
		return nil
	}
	out := new(BundleDeploymentOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleDeploymentResource) DeepCopyInto(out *BundleDeploymentResource) {
	*out = *in
	in.CreatedAt.DeepCopyInto(&out.CreatedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleDeploymentResource.
func (in *BundleDeploymentResource) DeepCopy() *BundleDeploymentResource {
	if in == nil {
		return nil
	}
	out := new(BundleDeploymentResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleDeploymentSpec) DeepCopyInto(out *BundleDeploymentSpec) {
	*out = *in
	in.StagedOptions.DeepCopyInto(&out.StagedOptions)
	in.Options.DeepCopyInto(&out.Options)
	if in.DependsOn != nil {
		in, out := &in.DependsOn, &out.DependsOn
		*out = make([]BundleRef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CorrectDrift != nil {
		in, out := &in.CorrectDrift, &out.CorrectDrift
		*out = new(CorrectDrift)
		**out = **in
	}
	if in.HelmChartOptions != nil {
		in, out := &in.HelmChartOptions, &out.HelmChartOptions
		*out = new(BundleHelmOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleDeploymentSpec.
func (in *BundleDeploymentSpec) DeepCopy() *BundleDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(BundleDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleDeploymentStatus) DeepCopyInto(out *BundleDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]GenericCondition, len(*in))
		copy(*out, *in)
	}
	if in.NonReadyStatus != nil {
		in, out := &in.NonReadyStatus, &out.NonReadyStatus
		*out = make([]NonReadyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ModifiedStatus != nil {
		in, out := &in.ModifiedStatus, &out.ModifiedStatus
		*out = make([]ModifiedStatus, len(*in))
		copy(*out, *in)
	}
	out.Display = in.Display
	if in.SyncGeneration != nil {
		in, out := &in.SyncGeneration, &out.SyncGeneration
		*out = new(int64)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]BundleDeploymentResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ResourceCounts = in.ResourceCounts
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleDeploymentStatus.
func (in *BundleDeploymentStatus) DeepCopy() *BundleDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(BundleDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleHelmOptions) DeepCopyInto(out *BundleHelmOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleHelmOptions.
func (in *BundleHelmOptions) DeepCopy() *BundleHelmOptions {
	if in == nil {
		return nil
	}
	out := new(BundleHelmOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleRef) DeepCopyInto(out *BundleRef) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleRef.
func (in *BundleRef) DeepCopy() *BundleRef {
	if in == nil {
		return nil
	}
	out := new(BundleRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BundleSummary) DeepCopyInto(out *BundleSummary) {
	*out = *in
	if in.NonReadyResources != nil {
		in, out := &in.NonReadyResources, &out.NonReadyResources
		*out = make([]NonReadyResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BundleSummary.
func (in *BundleSummary) DeepCopy() *BundleSummary {
	if in == nil {
		return nil
	}
	out := new(BundleSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComparePatch) DeepCopyInto(out *ComparePatch) {
	*out = *in
	if in.Operations != nil {
		in, out := &in.Operations, &out.Operations
		*out = make([]Operation, len(*in))
		copy(*out, *in)
	}
	if in.JsonPointers != nil {
		in, out := &in.JsonPointers, &out.JsonPointers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComparePatch.
func (in *ComparePatch) DeepCopy() *ComparePatch {
	if in == nil {
		return nil
	}
	out := new(ComparePatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapKeySelector) DeepCopyInto(out *ConfigMapKeySelector) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapKeySelector.
func (in *ConfigMapKeySelector) DeepCopy() *ConfigMapKeySelector {
	if in == nil {
		return nil
	}
	out := new(ConfigMapKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CorrectDrift) DeepCopyInto(out *CorrectDrift) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CorrectDrift.
func (in *CorrectDrift) DeepCopy() *CorrectDrift {
	if in == nil {
		return nil
	}
	out := new(CorrectDrift)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiffOptions) DeepCopyInto(out *DiffOptions) {
	*out = *in
	if in.ComparePatches != nil {
		in, out := &in.ComparePatches, &out.ComparePatches
		*out = make([]ComparePatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiffOptions.
func (in *DiffOptions) DeepCopy() *DiffOptions {
	if in == nil {
		return nil
	}
	out := new(DiffOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamResource) DeepCopyInto(out *DownstreamResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamResource.
func (in *DownstreamResource) DeepCopy() *DownstreamResource {
	if in == nil {
		return nil
	}
	out := new(DownstreamResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GenericCondition) DeepCopyInto(out *GenericCondition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericCondition.
func (in *GenericCondition) DeepCopy() *GenericCondition {
	if in == nil {
		return nil
	}
	out := new(GenericCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GenericMap.
func (in *GenericMap) DeepCopy() *GenericMap {
	if in == nil {
		return nil
	}
	out := new(GenericMap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsBundleDeploymentOptions) DeepCopyInto(out *GitOpsBundleDeploymentOptions) {
	*out = *in
	if in.YAML != nil {
		in, out := &in.YAML, &out.YAML
		*out = new(YAMLOptions)
		(*in).DeepCopyInto(*out)
	}
	if in.Kustomize != nil {
		in, out := &in.Kustomize, &out.Kustomize
		*out = new(KustomizeOptions)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsBundleDeploymentOptions.
func (in *GitOpsBundleDeploymentOptions) DeepCopy() *GitOpsBundleDeploymentOptions {
	if in == nil {
		return nil
	}
	out := new(GitOpsBundleDeploymentOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitOpsHelmOptions) DeepCopyInto(out *GitOpsHelmOptions) {
	*out = *in
	if in.ValuesFiles != nil {
		in, out := &in.ValuesFiles, &out.ValuesFiles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitOpsHelmOptions.
func (in *GitOpsHelmOptions) DeepCopy() *GitOpsHelmOptions {
	if in == nil {
		return nil
	}
	out := new(GitOpsHelmOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HelmOptions) DeepCopyInto(out *HelmOptions) {
	*out = *in
	in.GitOpsHelmOptions.DeepCopyInto(&out.GitOpsHelmOptions)
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = (*in).DeepCopy()
	}
	if in.TemplateValues != nil {
		in, out := &in.TemplateValues, &out.TemplateValues
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ValuesFrom != nil {
		in, out := &in.ValuesFrom, &out.ValuesFrom
		*out = make([]ValuesFrom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HelmOptions.
func (in *HelmOptions) DeepCopy() *HelmOptions {
	if in == nil {
		return nil
	}
	out := new(HelmOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IgnoreOptions) DeepCopyInto(out *IgnoreOptions) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]map[string]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make(map[string]string, len(*in))
				for key, val := range *in {
					(*out)[key] = val
				}
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IgnoreOptions.
func (in *IgnoreOptions) DeepCopy() *IgnoreOptions {
	if in == nil {
		return nil
	}
	out := new(IgnoreOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KustomizeOptions) DeepCopyInto(out *KustomizeOptions) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KustomizeOptions.
func (in *KustomizeOptions) DeepCopy() *KustomizeOptions {
	if in == nil {
		return nil
	}
	out := new(KustomizeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalObjectReference) DeepCopyInto(out *LocalObjectReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalObjectReference.
func (in *LocalObjectReference) DeepCopy() *LocalObjectReference {
	if in == nil {
		return nil
	}
	out := new(LocalObjectReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModifiedStatus) DeepCopyInto(out *ModifiedStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModifiedStatus.
func (in *ModifiedStatus) DeepCopy() *ModifiedStatus {
	if in == nil {
		return nil
	}
	out := new(ModifiedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonReadyResource) DeepCopyInto(out *NonReadyResource) {
	*out = *in
	if in.ModifiedStatus != nil {
		in, out := &in.ModifiedStatus, &out.ModifiedStatus
		*out = make([]ModifiedStatus, len(*in))
		copy(*out, *in)
	}
	if in.NonReadyStatus != nil {
		in, out := &in.NonReadyStatus, &out.NonReadyStatus
		*out = make([]NonReadyStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonReadyResource.
func (in *NonReadyResource) DeepCopy() *NonReadyResource {
	if in == nil {
		return nil
	}
	out := new(NonReadyResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NonReadyStatus) DeepCopyInto(out *NonReadyStatus) {
	*out = *in
	in.Summary.DeepCopyInto(&out.Summary)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NonReadyStatus.
func (in *NonReadyStatus) DeepCopy() *NonReadyStatus {
	if in == nil {
		return nil
	}
	out := new(NonReadyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Operation) DeepCopyInto(out *Operation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Operation.
func (in *Operation) DeepCopy() *Operation {
	if in == nil {
		return nil
	}
	out := new(Operation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverwrittenResource) DeepCopyInto(out *OverwrittenResource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverwrittenResource.
func (in *OverwrittenResource) DeepCopy() *OverwrittenResource {
	if in == nil {
		return nil
	}
	out := new(OverwrittenResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PerClusterState) DeepCopyInto(out *PerClusterState) {
	*out = *in
	if in.Ready != nil {
		in, out := &in.Ready, &out.Ready
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.WaitApplied != nil {
		in, out := &in.WaitApplied, &out.WaitApplied
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Pending != nil {
		in, out := &in.Pending, &out.Pending
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Modified != nil {
		in, out := &in.Modified, &out.Modified
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Orphaned != nil {
		in, out := &in.Orphaned, &out.Orphaned
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Missing != nil {
		in, out := &in.Missing, &out.Missing
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Unknown != nil {
		in, out := &in.Unknown, &out.Unknown
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotReady != nil {
		in, out := &in.NotReady, &out.NotReady
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PerClusterState.
func (in *PerClusterState) DeepCopy() *PerClusterState {
	if in == nil {
		return nil
	}
	out := new(PerClusterState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Resource) DeepCopyInto(out *Resource) {
	*out = *in
	in.PerClusterState.DeepCopyInto(&out.PerClusterState)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Resource.
func (in *Resource) DeepCopy() *Resource {
	if in == nil {
		return nil
	}
	out := new(Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceCounts) DeepCopyInto(out *ResourceCounts) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceCounts.
func (in *ResourceCounts) DeepCopy() *ResourceCounts {
	if in == nil {
		return nil
	}
	out := new(ResourceCounts)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
	out.LocalObjectReference = in.LocalObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusBase) DeepCopyInto(out *StatusBase) {
	*out = *in
	in.Summary.DeepCopyInto(&out.Summary)
	out.Display = in.Display
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]GenericCondition, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]Resource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.ResourceCounts = in.ResourceCounts
	if in.PerClusterResourceCounts != nil {
		in, out := &in.PerClusterResourceCounts, &out.PerClusterResourceCounts
		*out = make(map[string]*ResourceCounts, len(*in))
		for key, val := range *in {
			var outVal *ResourceCounts
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(ResourceCounts)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusBase.
func (in *StatusBase) DeepCopy() *StatusBase {
	if in == nil {
		return nil
	}
	out := new(StatusBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatusDisplay) DeepCopyInto(out *StatusDisplay) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatusDisplay.
func (in *StatusDisplay) DeepCopy() *StatusDisplay {
	if in == nil {
		return nil
	}
	out := new(StatusDisplay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValuesFrom) DeepCopyInto(out *ValuesFrom) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValuesFrom.
func (in *ValuesFrom) DeepCopy() *ValuesFrom {
	if in == nil {
		return nil
	}
	out := new(ValuesFrom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *YAMLOptions) DeepCopyInto(out *YAMLOptions) {
	*out = *in
	if in.Overlays != nil {
		in, out := &in.Overlays, &out.Overlays
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new YAMLOptions.
func (in *YAMLOptions) DeepCopy() *YAMLOptions {
	if in == nil {
		return nil
	}
	out := new(YAMLOptions)
	in.DeepCopyInto(out)
	return out
}
